# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

########### These MUST be filled in for a storm configuration
storm.zookeeper.servers:
     - "LEADER_HOST"
nimbus.seeds: ["LEADER_HOST"]
supervisor.slots.ports:
      - 6700
worker.heap.memory.mb: 2048

topology.metrics.consumer.register:
  - class: "com.github.staslev.storm.metrics.MetricReporter"
    argument:
      - "(.*.*)"
      - "com.github.staslev.storm.metrics.yammer.SimpleGraphiteStormMetricProcessor"
    parallelism.hint: 1


metric.reporter.graphite.report.period.sec: 30 
topology.builtin.metrics.bucket.size.secs: 30 
metric.reporter.graphite.report.host: "GRAPHITE_HOST"
metric.reporter.graphite.report.port: 2003
